### PR TITLE
Bump Mapbox version to 2.2.2 (bumps Leaflet to 0.7.5)

### PR DESCRIPTION
**Pull request by hale**
#### Mapbox 2.2.1 -> 2.2.2 // https://github.com/mapbox/mapbox.js/blob/v2.2.2/CHANGELOG.md#v222

> * Updates to Leaflet 0.7.5, fixing a performance regression in tile loading rooted in an upstream bug in Google Chrome's handling of transitionend events.

#### Leaflet 0.7.2 -> 0.7.5 //  https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md#075-september-2-2015

> **0.7.5 (September 2, 2015)**

>    * Fixed a regression that broke animation in Leaflet.markercluster. #3796

> **0.7.4 (September 1, 2015)**

>    * Fixed a bug introduced by a recent Chrome update that caused the map not to react to interactions until all tiles are loaded. #3689
>    * Fixed a bug where tile layers were not respecting their minZoom or maxZoom options (by @ivansanchez) #3778
>    * Improved detection of touch-capable web browsers, in particular fixing touch interactions in device emulation mode in Chrome and Firefox (by @ivansanchez) #3520 #3710
>    * Fixed a bug where tile layers with maxNativeZoom were not checking bounds properly (by @jlaxon) #3415
>    * Fixed a bug where popups were not remembering which layer originated them after calling bindPopup(popup) (by @Eschon) #3675
>    * Fixed a race condition between markers and zoom animation (by @perliedman) #3152
>    * Fixed a bug with Map.fitBounds padding (by @bsstoner). #2489
>    * Allow canvas paths to fire dblclick and contextmenu events (by @ivansanchez) #3482
>    * Allow canvas filled polygons to use the fillRule option (by @w8r) #3477
>    * Allow canvas lines to use lineCap and lineJoin options (by @northerneyes) #3156
>    * Updated bower definitions to comply with best practices (by @guptaso2) #2726 #3448

> **0.7.3 (May 23, 2014)**

>   * Added proper bower and component support (by @calvinmetcalf). #2561 #1903
>   * Fixed a bug where dragging the map outside the window caused an error on FF. #2610
>   * Fixed a bug where some taps on Android where not working, often falsely perceived as drags (by @axefrog). #2503
>   * Fixed a bug where clicks on Android were skipped when happened too fast. #2303
>   * Fixed a bug where calling setView (or similar methods) several times in succession could freeze the map. #2521 #2236 #2485
>   * Fixed a bug where Control.Layers wasn't properly removed (by @jack-kerouac). #2569
>   * Fixed a bug that caused TileLayer load event not to fire properly. #2510
>   * Fixed Canvas-based paths not triggering remove event when removed (by @adimitrov). #2486
>   * Fixed a bug where you could end up with fractional zoom after pinch-zooming in some cases (by @danzel. #2400 #1943

### CODE REVIEW

**Comment by dkniffin** [comment]
@hale This PR is now out of date. Mapbox just released [v2.3.0](https://github.com/mapbox/mapbox.js/releases/tag/v2.3.0). Can you update this PR?

Also, @idyll This PR has been sitting open for a few months. Any chance of getting it merged soon?

**Comment by dkniffin** [comment]
Actually, I made a new PR for 2.3.0 (#24)

**Comment by hale** [comment]
Closing in favour of https://github.com/aai/mapbox-rails/pull/25

**Comment by hale** [comment]
Ha, snap!

**Pull request closed without merging**
